// Package model2vec is the SW-259 THROWAWAY spike: a pure-Go, dependency-free
// re-implementation of Model2Vec static-embedding inference for one pinned
// artifact, minishlab/potion-code-16M-v2 (revision and SHA-256 pins in
// PINNED.md), checked against oracle fixtures generated by the official Python
// package (testdata/oracle/).
//
// It exists to answer one question before SW-262 rebuilds parsers and the index
// schema around a static embedder: can graphi reproduce the reference
// tokenizer + float16 lookup + mean pooling + L2 normalisation EXACTLY, in Go,
// CGo-free and with zero egress? The answer is written as a GO/NO-GO record in
// docs/rc/model2vec-spike.md. Nothing in the product imports this package, it
// registers no scheme in engine/embed, and SW-262 either supersedes or deletes
// it (isolation_test.go proves the removal would be complete).
//
// What is implemented is exactly what the pinned tokenizer.json uses and
// nothing more: a BertNormalizer (clean_text, handle_chinese_chars,
// strip_accents, lowercase), a BertPreTokenizer, a WordPiece model with the
// "##" continuation prefix, the two added tokens [PAD]/[UNK], right truncation
// at 512 tokens, and no post-processor. The safetensors reader handles one F16
// tensor; the float16 codec is written here (f16.go). Determinism: pooling sums
// in token-index order into float32 accumulators, the reference's float16
// rounding points are mirrored one by one (embed.go documents each), and no
// SIMD or reassociation is assumed anywhere.
package model2vec
