// Package static's canonical decomposition table (NFD). The table mirrors
// the SW-259 spike's nfd_table.go — generated by a Python script from
// `unicodedata` 15.1, the same source tokenizers uses.
//
// The table covers every codepoint with a non-trivial canonical
// decomposition; a codepoint not in the table has no decomposition and is
// passed through unchanged by appendNFD.
package static

// appendNFD appends the full canonical decomposition of r to dst. Hangul
// syllables are decomposed algorithmically; everything else through the
// generated table (nfd_table.go). A rune without a canonical decomposition
// is appended unchanged.
//
// Canonical REORDERING of combining marks is deliberately not performed: the
// only consumer strips every nonspacing mark immediately afterwards, and the
// order among characters that survive is unaffected.
func appendNFD(dst []rune, r rune) []rune {
	// Hangul syllable decomposition (Unicode §3.12).
	const (
		hangulSBase  = 0xAC00
		hangulLBase  = 0x1100
		hangulVBase  = 0x1161
		hangulTBase  = 0x11A7
		hangulTCount = 28
		hangulNCount = 21 * hangulTCount
		hangulSCount = 19 * hangulNCount
	)
	if s := r - hangulSBase; s >= 0 && s < hangulSCount {
		dst = append(dst, hangulLBase+s/hangulNCount, hangulVBase+(s%hangulNCount)/hangulTCount)
		if t := s % hangulTCount; t != 0 {
			dst = append(dst, hangulTBase+t)
		}
		return dst
	}
	// Linear scan over the sorted table — small enough (nfdKeys has <2100
	// entries) that the spike's binary-search approach is also fine; we use
	// a linear scan here for simplicity and to keep the nfd_table.go file
	// purely data. nfdValues is stored as []string (one rune per code unit
	// since the SW-259 table is BMP-only) and we decode each code unit
	// back to a rune here.
	for i := 0; i < len(nfdKeys); i++ {
		if nfdKeys[i] == r {
			for _, c := range nfdValues[i] {
				dst = append(dst, rune(c))
			}
			return dst
		}
		if nfdKeys[i] > r {
			break
		}
	}
	return append(dst, r)
}
