# GENERATED by cmd/gen-packaging — regenerate per release:
#   go run ./cmd/gen-packaging -version vX.Y.Z -sums SHA256SUMS
class Graphi < Formula
  desc "Local-first, CGo-free code-intelligence engine"
  homepage "https://github.com/samibel/graphi"
  version "0.0.0"
  on_macos do
    on_arm do
      url "https://github.com/samibel/graphi/releases/download/0.0.0/graphi-darwin-arm64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/samibel/graphi/releases/download/0.0.0/graphi-darwin-amd64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/samibel/graphi/releases/download/0.0.0/graphi-linux-arm64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/samibel/graphi/releases/download/0.0.0/graphi-linux-amd64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end
  def install
    bin.install Dir["graphi-*"].first => "graphi"
  end
  test do
    system "#{bin}/graphi", "version"
  end
end
