package main

import (
	"fmt"
	"os"
	"os/exec"
	"runtime"
)

// installShURL / installPS1URL are the raw URLs of the committed one-line
// installers (generated by cmd/gen-install from internal/release.ReleaseTargets).
const (
	installShURL  = "https://raw.githubusercontent.com/samibel/graphi/main/install.sh"
	installPS1URL = "https://raw.githubusercontent.com/samibel/graphi/main/install.ps1"
)

// upgradeCmd describes the OS-shell command that re-execs the installer.
type upgradeCmd struct {
	Name string   // the shell program (sh / powershell)
	Args []string // its arguments
	Env  []string // additional env vars forwarded to the child (e.g. GRAPHI_VERSION)
}

// String renders the command as a single copy-pasteable line, prefixing any
// forwarded env vars.
func (c upgradeCmd) String() string {
	prefix := ""
	for _, e := range c.Env {
		prefix += e + " "
	}
	return prefix + c.Name + " " + shJoin(c.Args)
}

// shJoin joins args for display, quoting the single combined script argument so
// the printed line is copy-pasteable.
func shJoin(args []string) string {
	out := ""
	for i, a := range args {
		if i > 0 {
			out += " "
		}
		if a == "-c" || a == "-Command" || a == "-NoProfile" {
			out += a
			continue
		}
		out += "'" + a + "'"
	}
	return out
}

// buildUpgradeCommand constructs the OS-shell command that re-execs the one-line
// installer. It is a PURE function (no I/O, no dial) so it is unit-testable
// offline. goos selects the platform; version, when non-empty, is forwarded into
// the child env as GRAPHI_VERSION so the child installer pins that release.
//
// The graphi binary itself NEVER opens a socket: the child `curl`/`iwr` does the
// network I/O, so the egress canary stays green by construction.
func buildUpgradeCommand(goos, version string) upgradeCmd {
	var c upgradeCmd
	if goos == "windows" {
		script := fmt.Sprintf("iwr -useb %s | iex", installPS1URL)
		c = upgradeCmd{
			Name: "powershell",
			Args: []string{"-NoProfile", "-Command", script},
		}
	} else {
		script := fmt.Sprintf("curl -fsSL %s | sh", installShURL)
		c = upgradeCmd{
			Name: "sh",
			Args: []string{"-c", script},
		}
	}
	if version != "" {
		c.Env = []string{"GRAPHI_VERSION=" + version}
	}
	return c
}

// runUpgrade implements `graphi upgrade`. It re-execs the committed one-line
// installer through the OS shell — the SINGLE user-initiated outbound in graphi,
// and NEVER automatic (there is no startup version check anywhere). The child
// process performs the network I/O; the graphi binary opens no socket itself, so
// the egress canary stays green by construction.
//
//	graphi upgrade [-print]
//
// With -print the exact installer command is printed to stdout and nothing is
// executed (no dial). GRAPHI_VERSION, if set, is forwarded to pin a release.
func runUpgrade(args []string) int {
	printOnly := false
	for _, a := range args {
		switch a {
		case "-print", "--print":
			printOnly = true
		case "-h", "--help":
			fmt.Println("usage: graphi upgrade [-print]")
			fmt.Println("  re-execs the one-line installer (the single user-initiated outbound; never automatic).")
			fmt.Println("  -print   print the exact installer command and exit (no network).")
			fmt.Println("  set GRAPHI_VERSION=<tag> to pin a release.")
			return 0
		default:
			fmt.Fprintf(os.Stderr, "graphi upgrade: unknown argument: %s\n", a)
			return 1
		}
	}

	cmd := buildUpgradeCommand(runtime.GOOS, os.Getenv("GRAPHI_VERSION"))

	if printOnly {
		fmt.Println(cmd.String())
		return 0
	}

	c := exec.Command(cmd.Name, cmd.Args...) //nolint:gosec // fixed installer command; user-initiated upgrade
	c.Env = append(os.Environ(), cmd.Env...)
	c.Stdin = os.Stdin
	c.Stdout = os.Stdout
	c.Stderr = os.Stderr
	if err := c.Run(); err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return ee.ExitCode()
		}
		fmt.Fprintf(os.Stderr, "graphi upgrade: %v\n", err)
		return 1
	}
	return 0
}
