package client

import (
	"os"
	"path/filepath"
	"testing"
)

func TestGeneratedMarkerDetector(t *testing.T) {
	root := t.TempDir()
	write := func(rel, content string) {
		t.Helper()
		p := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("gen/api.go", "// Code generated by protoc. DO NOT EDIT.\npackage gen\n")
	write("gen/tagged.ts", "/* @generated */\nexport const x = 1\n")
	write("src/handwritten.go", "package src\n\nfunc Real() {}\n")

	detect := GeneratedMarkerDetector(root)
	if !detect("gen/api.go") {
		t.Fatal("expected Code generated marker to be detected")
	}
	if !detect("gen/tagged.ts") {
		t.Fatal("expected @generated marker to be detected")
	}
	if detect("src/handwritten.go") {
		t.Fatal("handwritten file must not be flagged")
	}
	if detect("missing/nope.go") {
		t.Fatal("unreadable file must report false")
	}
	if detect("") {
		t.Fatal("empty path must report false")
	}
}
