/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Versioned Go<->TS single source of truth for the read-only HTTP REST + SSE surface. SchemaVersion is the ENVELOPE/contract version (versions the wire shape consumed by TS/web/TUI/VS Code clients); the engine EP-002 payload schema embedded verbatim inside `envelope.payload` is versioned independently. R5 drift-gate: the request header X-Graphi-Schema-Version is OPTIONAL; the response version stamp is MANDATORY.
 */
export interface GraphiHTTPSurfaceContractSW044 {
  [k: string]: unknown;
}
/**
 * Success data response. payload carries the engine canonical bytes verbatim, byte-identical to MCP/CLI output (parity by construction).
 *
 * This interface was referenced by `GraphiHTTPSurfaceContractSW044`'s JSON-Schema
 * via the `definition` "envelope".
 */
export interface Envelope {
  schema_version: 1;
  /**
   * EP-002 engine payload (typed by the engine's own schema).
   */
  payload: {
    [k: string]: unknown;
  };
}
/**
 * The single error shape shared by every REST error response AND the SSE event:error frame.
 *
 * This interface was referenced by `GraphiHTTPSurfaceContractSW044`'s JSON-Schema
 * via the `definition` "errorEnvelope".
 */
export interface ErrorEnvelope {
  schema_version: 1;
  error: {
    code: "bad_request" | "not_found" | "schema_mismatch" | "unavailable" | "internal";
    /**
     * Sanitized, client-safe message. NEVER a raw engine error string, stack trace, or filesystem path.
     */
    message: string;
  };
}
/**
 * The /contract capability-negotiation document (AC-6).
 *
 * This interface was referenced by `GraphiHTTPSurfaceContractSW044`'s JSON-Schema
 * via the `definition` "contract".
 */
export interface Contract {
  schema_version: 1;
  /**
   * Negotiable read resources: query/<op>, search, analyze/<analyzer>.
   */
  resources: string[];
  /**
   * SSE event types observable on /events (data + framing events).
   */
  streams: string[];
}
/**
 * Logical shape of one SSE frame on /events. On the wire it is encoded as the lines `event: <type>`, `id: <monotonic per-connection seq>`, `data: <json>`, followed by a blank line. The first frame is always event:ready stamping the schema_version; event:bye is the terminal completion frame; event:error carries an errorEnvelope.
 *
 * This interface was referenced by `GraphiHTTPSurfaceContractSW044`'s JSON-Schema
 * via the `definition` "sseFrame".
 */
export interface SseFrame {
  /**
   * Event type: a data event (e.g. ingest-completed) or a framing event (ready|bye|error).
   */
  event: string;
  /**
   * Monotonic per-connection sequence.
   */
  id: number;
  /**
   * event-specific JSON: {schema_version} for ready, {} for bye, errorEnvelope for error, observe.Event for data events.
   */
  data: {
    [k: string]: unknown;
  };
}
