"""Generate nfd_table.go: the full canonical (NFD) decomposition of every code point
that has one, excluding Hangul syllables (decomposed algorithmically in nfd.go).

Usage (from the repository root):
    python3 internal/spike/model2vec/testdata/gen_unicode_tables.py > internal/spike/model2vec/nfd_table.go
    gofmt -w internal/spike/model2vec/nfd_table.go

The Go standard library carries the Unicode category tables (used for Mn, C, P, ...)
but not the decomposition data, and the spike may not add golang.org/x/text
(go.mod must stay unchanged), so the table is generated once from Python's
unicodedata and checked in.
"""
import sys
import unicodedata

keys = []
values = []
for cp in range(0x110000):
    if 0xD800 <= cp <= 0xDFFF:
        continue
    ch = chr(cp)
    d = unicodedata.decomposition(ch)
    if not d or d.startswith("<"):
        continue  # no decomposition, or a compatibility (not canonical) one
    full = unicodedata.normalize("NFD", ch)
    if full == ch:
        continue
    keys.append(cp)
    values.append(full)

out = sys.stdout
out.write("// Code generated by testdata/gen_unicode_tables.py")
out.write(f" (Python {sys.version.split()[0]}, unicodedata {unicodedata.unidata_version}); DO NOT EDIT.\n\n")
out.write("package model2vec\n\n")
out.write("// nfdKeys is the sorted list of code points with a canonical decomposition\n")
out.write("// (Hangul syllables excluded); nfdValues[i] is the full NFD of nfdKeys[i].\n")
out.write(f"// {len(keys)} entries.\n")
out.write("var nfdKeys = []rune{\n")
for i in range(0, len(keys), 8):
    out.write("\t" + " ".join(f"0x{k:04X}," for k in keys[i : i + 8]) + "\n")
out.write("}\n\n")
out.write("var nfdValues = []string{\n")
for v in values:
    esc = "".join(f"\\u{ord(c):04X}" if ord(c) <= 0xFFFF else f"\\U{ord(c):08X}" for c in v)
    out.write(f'\t"{esc}",\n')
out.write("}\n")
