package search_test

import (
	"context"
	"sync/atomic"
	"testing"

	"github.com/samibel/graphi/core/graphstore"
	"github.com/samibel/graphi/core/model"
	"github.com/samibel/graphi/engine/embed"
	"github.com/samibel/graphi/engine/search"
)

// findNode returns the seeded node with the given qualified name.
func findNode(t *testing.T, nodes []model.Node, qn string) model.Node {
	t.Helper()
	for _, n := range nodes {
		if n.QualifiedName() == qn {
			return n
		}
	}
	t.Fatalf("node %q not found among %d seeded nodes", qn, len(nodes))
	return model.Node{}
}

// countingEmbedder wraps the deterministic mock and counts Embed calls so a test
// can assert exactly how many embeddings occurred on a given path (the
// reload-without-re-embed contract). Determinism is inherited from the mock.
type countingEmbedder struct {
	inner *embed.MockEmbedder
	calls int64 // number of texts embedded
}

func (c *countingEmbedder) ID() string { return c.inner.ID() }
func (c *countingEmbedder) Dim() int   { return c.inner.Dim() }
func (c *countingEmbedder) Embed(ctx context.Context, texts []string) ([][]float32, error) {
	atomic.AddInt64(&c.calls, int64(len(texts)))
	return c.inner.Embed(ctx, texts)
}

// index→search e2e: vectors generated by the index pass, persisted to the durable
// SQLite table, reloaded into a FRESH in-memory index, and served by the search
// service produce non-empty cosine-ranked hits in deterministic order — AND the
// node vectors are NOT re-embedded on the reload path (only the single query is
// embedded at search time).
func TestSemanticSearch_IndexPersistReloadE2E(t *testing.T) {
	ctx := context.Background()
	st := graphstore.NewMemStore()
	defer st.Close()
	seedStore(t, st)

	dir := t.TempDir()

	// --- index --semantic pass: generate + persist (counts N node embeds). ---
	genEmb := &countingEmbedder{inner: embed.NewMockEmbedder(16)}
	genReg := embed.NewRegistry()
	genReg.Register(genEmb)
	nodes, err := st.Nodes(ctx, graphstore.Query{})
	if err != nil {
		t.Fatalf("Nodes: %v", err)
	}
	table, err := embed.OpenSQLiteVectorTable(ctx, dir, genEmb.ID(), genEmb.Dim())
	if err != nil {
		t.Fatalf("open table: %v", err)
	}
	if _, err := embed.GenerateAndPersist(ctx, genReg, nodes, embed.NewIndex(), table); err != nil {
		t.Fatalf("GenerateAndPersist: %v", err)
	}
	_ = table.Close()
	if genEmb.calls != int64(len(nodes)) {
		t.Fatalf("index pass embedded %d, want %d (one per node)", genEmb.calls, len(nodes))
	}

	// --- restart: a fresh embedder + fresh index Rebuilt from durable storage. ---
	srchEmb := &countingEmbedder{inner: embed.NewMockEmbedder(16)}
	srchReg := embed.NewRegistry()
	srchReg.Register(srchEmb)
	reloadTable, err := embed.OpenSQLiteVectorTable(ctx, dir, srchEmb.ID(), srchEmb.Dim())
	if err != nil {
		t.Fatalf("reopen table: %v", err)
	}
	defer reloadTable.Close()
	reloaded := embed.NewIndex()
	if err := reloaded.Rebuild(ctx, reloadTable); err != nil {
		t.Fatalf("Rebuild: %v", err)
	}
	// Rebuild must NOT have embedded anything — it is a pure local read.
	if srchEmb.calls != 0 {
		t.Fatalf("reload re-embedded %d texts; want 0 (pure local read)", srchEmb.calls)
	}

	svc := search.New(st).WithSemantic(srchReg, reloaded, st)
	// Query with the exact text the target node was embedded with (NodeText) so the
	// exact-match node scores cosine 1.0 and ranks first deterministically.
	target := findNode(t, nodes, "pkg/foo.ParseGraph")
	res, err := svc.SemanticSearch(ctx, embed.NodeText(target), 10)
	if err != nil {
		t.Fatalf("SemanticSearch: %v", err)
	}
	if !res.Available {
		t.Fatal("Available = false after reload, want true")
	}
	if len(res.Hits) == 0 {
		t.Fatal("no hits after index→persist→reload→search (empty-index bug regressed)")
	}
	// The exact-match node ranks first; the query embed is the ONLY embed at search.
	if res.Hits[0].QualifiedName != "pkg/foo.ParseGraph" {
		t.Fatalf("top hit = %q, want pkg/foo.ParseGraph", res.Hits[0].QualifiedName)
	}
	if srchEmb.calls != 1 {
		t.Fatalf("search embedded %d texts; want exactly 1 (the query only)", srchEmb.calls)
	}
	// Deterministic across repeated queries.
	res2, _ := svc.SemanticSearch(ctx, embed.NodeText(target), 10)
	b1, _ := search.MarshalSemantic(res)
	b2, _ := search.MarshalSemantic(res2)
	if string(b1) != string(b2) {
		t.Fatalf("non-deterministic semantic results after reload")
	}
}
